# -*- coding: utf-8 -*-
"""Tugas1_Job_7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gNSb3Z7mGU9hYt9rPioCbvr8tggsAsN1
"""

# TUGAS NO.1
# KEUNTUNGAN ASET PERUSAHAAN


import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

dataset = pd.read_csv("aset.csv", sep=';')
dataset

from sklearn.preprocessing import LabelEncoder

enc = LabelEncoder()

dataset['usia_aset'] = enc.fit_transform(dataset['usia_aset'].values)
dataset['nilai_saing'] = enc.fit_transform(dataset['nilai_saing'].values)
dataset['jenis'] = enc.fit_transform(dataset['jenis'].values)
dataset['keuntungan'] = enc.fit_transform(dataset['keuntungan'].values)

dataset

atr_dataset = dataset.drop(columns="keuntungan")
atr_dataset

cls_dataset = dataset['keuntungan']
cls_dataset

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.tree import DecisionTreeClassifier

xtrain, xtest, ytrain, ytest = train_test_split(atr_dataset, cls_dataset, test_size=0.2, random_state=1)
tree_dataset = DecisionTreeClassifier(random_state=1)
tree_dataset.fit(xtrain, ytrain)

y_pred = tree_dataset.predict(xtest)
cm = confusion_matrix(ytest, y_pred)
print("Confusion Matrix")
print(cm)
akurasi = classification_report(ytest, y_pred)
print("Tingkat Akurasi ")
print("Akurasi:", akurasi)
akurasi = accuracy_score(ytest, y_pred)
print("Tingkat Akurasi: %d persen" %(akurasi*100))

from sklearn.tree import export_graphviz
export_graphviz(tree_dataset, out_file="aset.dot", class_names=["A","B","C","D"],
                feature_names=atr_dataset.columns, impurity=False, filled=True)

import graphviz

with open("aset.dot") as fig:
    dot_graph = fig.read()
    graph = graphviz.Source(dot_graph)

graph.view()